### ISSUE TITLE
突然不要下载了 如何停止?

### ISSUE THREAD

**Issue by zhanghan328** [dixudx/tumblr-crawler#11]

**Comment by dixudx** [comment]
@zhanghan328 Just press `Ctrl+C` to stop the downloading.

**Comment by zhanghan328** [comment]
ssh 登录远程服务器这样操作没用.

**Comment by dixudx** [comment]
@zhanghan328 Try to run `ps -ef | grep tumblr` to find the process id `$PID`. And then run `kill -s 9 $PID`

**Comment by zhanghan328** [comment]
ssh 远程登录情况下下载时一直输出下载信息 按啥都没用啊

**Comment by dixudx** [comment]
@zhanghan328 Just open another SSH terminal to kill that process.

**Comment by zhanghan328** [comment]
Thanks，the professional driver.  would you mind add the 91？
