### ISSUE TITLE
作者你提供Shadowsocks的代理设置是错误的

### ISSUE THREAD

**Issue by GGGYYYIII** [dixudx/tumblr-crawler#115]
作者你提供的全局代理设置是错误的，引号是大写的，http://jsonlint.com/ 验证也是错误，正确应该是这个
{
  "http":"http://127.0.0.1:1080",
  "https":"https://127.0.0.1:1080"
}

**Comment by dixudx** [comment]
哪里错误了，readme里面不就是这个吗
