### ISSUE TITLE
Can not download content from a tumblr site that doesn't end with tumblr.com

### ISSUE THREAD

**Issue by WilliamZY** [dixudx/tumblr-crawler#16]
there was a tumblr site with the address :http://laster.tumblr.com/
but it has recently changed its address to http://t.misoraskyhigh.com/
when writing "laster" in the sites.txt, it will not start download and the program doesn't show any notices of error

BTW, puting "t" in the sites.txt doesn't help

**Comment by dixudx** [comment]
@WilliamZY It works fine on my box. Actually the http://laster.tumblr.com/ is redirected to http://t.misoraskyhigh.com/. Nothing else has changed.

You can still download with writing `laster` in `sites.txt`.

One more thing you may have to pay attention to, is the **proxy**. If you have to bypass the firewall, please configure your proxy before moving on. Please refer to [proxy setting](https://github.com/dixudx/tumblr-crawler#use-proxies-optional).

And [proxies_sample1.json](https://github.com/dixudx/tumblr-crawler/blob/master/proxies_sample1.json) and [proxies_sample2.json](https://github.com/dixudx/tumblr-crawler/blob/master/proxies_sample2.json) are good samples for you to get started.
