### ISSUE TITLE
有关代理

### ISSUE THREAD

**Issue by kaliludan** [dixudx/tumblr-crawler#19]
Hello, I am a beginner of Python that is learning crawler these days, I am really confused by the proxies issue. I tried to follow the lead of samples, but it still won't work.

it says:
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.

Could you make the sample more specific? the proxy that I am using is called greenvpn.

**Comment by dixudx** [comment]
@kaliludan From the error, it seems you have not installed `PySocks>=1.5.6`.

Please using `pip` to install all the needed dependencies.

```sh
$ pip install -r requirements.txt
```

**Comment by kaliludan** [comment]
it helps, thank you!
