### ISSUE TITLE
Downloading likes from a tumblr

### ISSUE THREAD

**Issue by spacekittylasereyes** [dixudx/tumblr-crawler#21]
Hello,

First of all thank you very much, works great. The issue is that I failed to download likes from a tumblr blog. I tried writing the website in tumblr.com/liked/by/[tumblr name] format in sites.txt file but had no results. Is it possible to download likes from a tumblr blog using this code? If it is, can you please help?

Thank you,

spacekittylasereyes

**Comment by dixudx** [comment]
Thanks for using this tool.

1. Currently, this snippet only supports downloading videos/photos from tumblr blog. You can refer to [Configuration and Downloading](https://github.com/dixudx/tumblr-crawler#configuration-and-downloading) for more detailed explanation.

2. Actually there is a way to download likes from a tumblr blog. You can refer to [How To Retrieve Blog's Likes](https://www.tumblr.com/docs/en/api/v2#blog-likes), which will require an OAuth token.
