### ISSUE TITLE
Video player may be loaded fail, cause the url build fail.

### ISSUE THREAD

**Issue by levonlin** [dixudx/tumblr-crawler#22]
In function `_handle_medium_url`, the `post["video-player"][1]` might not have the field `#test` when the video player in a post loaded fail. Such as this [post](http://pandadandan.tumblr.com/post/155338512591/%E7%AB%A5%E9%A1%8F%E5%B7%A8%E4%B9%B3%E7%9B%B4%E6%92%AD%E9%9C%B2%E9%BB%9E%E6%83%B3%E8%B5%B7%E9%83%BD%E8%88%88%E5%A5%AE%E7%9C%8B%E8%A6%8B%E5%85%A9%E7%89%87%E4%B9%B3%E9%9B%B2%E7%9C%9F%E7%9A%84%E5%8F%A3%E6%B0%B4%E9%83%BD%E6%B5%81%E5%87%BA%E4%BE%86-%E7%AB%A5%E9%A1%8F%E5%B7%A8%E4%B9%B3%E5%9C%A8%E6%AD%A4), the `post["video-player"][1]` just get `OrderedDict([(u'@max-width', u'500')])`.

Add some codes to handle this error please:
```python
try:
    video_player = post["video-player"][1]["#text"]
except:
   return None
```

**Comment by dixudx** [comment]
@levonlin Please pull the latest code and retry.

**Comment by levonlin** [comment]
Ok, it seems new code would auto ignore the `#text` data which does not exist.:joy:
