### ISSUE TITLE
Failed when the site does not exist

### ISSUE THREAD

**Issue by zhihuya** [dixudx/tumblr-crawler#23]
[WinError 10060] 由于
连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
在proxies.json写入
```
{
    "http": "127.0.0.1:14225",
    "SOCKS": "127.0.0.1:14226"
}
```

**Comment by zhihuya** [comment]
使用的蓝灯
HTTP(S)代理服务器：127.0.0.1:14225
SOCKS代理服务器：127.0.0.1:14226
请问该怎么配置

**Comment by dixudx** [comment]
```json
{
    "http": "socks5://127.0.0.1:14226",
    "https": "socks5://127.0.0.1:14226"
}
```

Please refer to [代理配置](https://github.com/dixudx/tumblr-crawler/blob/master/README_CN.md#使用代理-可选)

**Comment by zhihuya** [comment]
F:\PycharmProjects\tumblr\tumblr-crawler (master)
$ python tumblr-photo-video-ripper.py
You are using proxies.
{'http': 'socks5://127.0.0.1:14226', 'https': 'socks5://127.0.0.1:14226'}
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\xmltodict.py", line 309, in parse

    parser.ParseFile(xml_input)
TypeError: argument must have 'read' attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 285, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 149, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 162, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 165, in download_media
    self.download_photos(site)
  File "tumblr-photo-video-ripper.py", line 176, in download_photos
    self._download_media(site, "photo", START)
  File "tumblr-photo-video-ripper.py", line 194, in _download_media
    data = xmltodict.parse(response.content)
  File "C:\Python35\lib\site-packages\xmltodict.py", line 311, in parse

    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

**Comment by zhihuya** [comment]
还是出错了

**Comment by dixudx** [comment]
Please pull the latest code and retry.

**Comment by zhihuya** [comment]
I'm using the lasted code:tumblr-photo-video-ripper.py, but still failed.
In the sites.txt ,I wrote:
```
crispyninjakitten,alwxyouzai
crispyninjakitten2,alwxyouzai2
```

**Comment by Jungley8** [comment]
`
{
    "http": "http://127.0.0.1:1080",
    "https": "https://127.0.0.1:1080"
}
`
用ss代理 配置 这样也ok ，ss不知道怎么配 socks

**Comment by dixudx** [comment]
@Jungley8 

For shadowsocks,

```json
{
    "http": "socks5://127.0.0.1:1080",
    "https": "socks5://127.0.0.1:1080"
}
```

You can find [the configuration](https://github.com/dixudx/tumblr-crawler/blob/master/README_CN.md#使用代理-可选)
