### ISSUE TITLE
not well format 错误 在某些sites出现

### ISSUE THREAD

**Issue by Rockyzsu** [dixudx/tumblr-crawler#24]
try:
                data = xmltodict.parse(response.content)
            except Exception ,e:
                print e
                break

在分析data这句出现的错误， e 的错误是not well format出错，是不是因为网站屏蔽的原因？

这个错误只在部分的用户名上出现，比如 tsukimitsuki
是不是日文的就会有问题？

**Comment by dixudx** [comment]
This has nothing to do with the language.

The site you mentioned here does not exist. So the `response.content` may raise some exception.

Already fixed in  [this commit](https://github.com/dixudx/tumblr-crawler/commit/aed2acaf138024f61bfc01ff459b58d0c9aee7fd)

**Comment by Rockyzsu** [comment]
@dixudx 但是我用你最新的fixed过的版本也遇到这样的问题，你的404不能捕捉到这个异常，所以我才上来提问的。 网站是存在的，我也打开过。

**Comment by dixudx** [comment]
@Rockyzsu You're right. Good catch. Will fix later.

One more thing, the site you mentioned requires logging in. The apis I am using can't handle such sites.
