### ISSUE TITLE
Add a warning if wrong link is given by user

### ISSUE THREAD

**Issue by JohnCoconut** [dixudx/tumblr-crawler#25]
I accidentally entered a wrong tumblr address which does not exisit. The scrips report a error that XML tag is broken. Can you add a warning if wrong address is entered?

**Comment by dixudx** [comment]
Please pull the latest code.

This feature has already been update in [this commit](https://github.com/dixudx/tumblr-crawler/commit/aed2acaf138024f61bfc01ff459b58d0c9aee7fd)
