### ISSUE TITLE
pathon小白一枚，请问下输入命令都提示语法错误该怎么办？

### ISSUE THREAD

**Issue by fxd2006** [dixudx/tumblr-crawler#27]
在windows环境下，安装的python环境；
可输入命令一直说语法错误；
![untitled](https://cloud.githubusercontent.com/assets/11625036/24761450/f40ca786-1b1d-11e7-8b1d-4c629ff082c5.jpg)

该怎么做呢？纯小白一枚，跪求指教

**Comment by dixudx** [comment]
你的命令输错地方了，你现在是在python shell里面输入的命令，所以是出问题的。

应该退出python的shell 环境，输入`exit()`退出。然后继续运行你的那些命令。

**Comment by fxd2006** [comment]
在这里输入exit(),程序就关了啊？
