### ISSUE TITLE
执行脚本时说导入错误？

### ISSUE THREAD

**Issue by fxd2006** [dixudx/tumblr-crawler#28]
![qq 20170408133246](https://cloud.githubusercontent.com/assets/11625036/24826022/619b03f0-1c5f-11e7-9ec0-d72bc0345335.png)
错误信息如上图

**Comment by fxd2006** [comment]
已经成功执行过命令；pip install requests xmltodict；
所以图上的git命令错误可以忽略的；

**Comment by dixudx** [comment]
运行`pip install -U xmltodict six "requests>=2.10.0" "PySocks>=1.5.6"`。

详细文档见[这里](https://github.com/dixudx/tumblr-crawler/blob/master/README_CN.md#小白见这里)
