### ISSUE TITLE
proxies.json 文件为空，报错， python 2.11 

### ISSUE THREAD

**Issue by yustarg** [dixudx/tumblr-crawler#3]
Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 206, in <module>
    illegal_json()
  File "tumblr-photo-video-ripper.py", line 190, in illegal_json
    print(u"文件proxies.json格式非法.\n"
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

不知道为何，用vpn，直接把这段全注掉就ok了

**Comment by dixudx** [comment]
Aha, it is the unicode error. Please check whether you are using some Chinese characters including punctuation marks (e.g. quotes, curly braces and etc).

What is the content in your `proxies.json`. Have you validated on http://jsonlint.com/.

If you are using vpn in global mode, you can leave `proxies.json` empty. And the script won't read it afterwards.

**Comment by dixudx** [comment]
Pls pull the latest code.

Already fix the issue by #5 .
