### ISSUE TITLE
xml parsing error

### ISSUE THREAD

**Issue by minkang2014** [dixudx/tumblr-crawler#33]
I met the same problem as @Yodamt in issue #31, it looks like this:

>  File "tumblr-photo-video-ripper.py", line 199, in _download_media
    data = xmltodict.parse(response.content)
  File "C:\Python27\lib\site-packages\xmltodict.py", line 330, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 21, column 2311

I inspected the data and 发现response.content里面的对应位置是引号后面跟了一个\b，我不确定python是不是因此就把那个引号删掉了然后导致xml解析不过。

我按照Issue #31里面给出的方法把MEDIA_NUM改成了100，然而并没什么用。

**Comment by minkang2014** [comment]
`<post id="12345678" xxx="xxxxx" reblogged-root-title="\bxxxxxxx" />`
大概类似这样

**Comment by dixudx** [comment]
I guess the web page you're visiting may contain some non-unicode characters, which may cause xml.parser failed to parse successfully. This bug is quite tricky, which is not caused by my script. And it does not happen too often.

**Comment by minkang2014** [comment]
Okay, thanks for your reply.
I'm using a `replace` function as a temporary solution to prevent the program from crash.

**Comment by s4uxnat** [comment]
@minkang2014 How can I temporary solve this problem by using `replace` function ? 
I find this bug and not get solution yet

**Comment by dixudx** [comment]
@s4uxnat Change [tumblr-photo-video-ripper.py#L199](https://github.com/dixudx/tumblr-crawler/blob/master/tumblr-photo-video-ripper.py#L199) to `data = xmltodict.parse(response.content.replace("\b", ""))`

**Comment by s4uxnat** [comment]
@dixudx  I tried, same error.
I noticed some **emoji** character in tag `<photo-caption>` , can this lead to error?

**Comment by dixudx** [comment]
@s4uxnat Yes, probably.

If so, I think we'd better need a patch to fix this. Will update later.

**Comment by s4uxnat** [comment]
@dixudx Ok I found something else the script L207 `post` data;
the tag `<tumblelog>` contains `title="I♡shared…"` that `♡` is not a legal character
