### ISSUE TITLE
打开就闪退，要不就是只显示你在使用代理

### ISSUE THREAD

**Issue by weigeloveu** [dixudx/tumblr-crawler#42]
log在哪找啊，只创建空目录，没文件。

**Comment by weigeloveu** [comment]
C:\Users\weigeloveu\Downloads\tumblr-crawler-master>python tumblr-photo-video-ripper.py yamato2520
You are using proxies.
{'https': 'socks5://127.0.0.1:1080', 'http': 'socks5://127.0.0.1:1080'}
用命令行下载就卡在这里。
用site.txt下载就闪退

**Comment by dixudx** [comment]
log就在前台显示，正常print。

你的代理确定能work，我给的只是示例，你要确保自己本地有proxy的。

**Comment by weigeloveu** [comment]
多谢了，昨天在单位网不是很稳定，梯子是没问题的，我发现了另一个问题，site.txt只能下载前两个站

**Comment by weigeloveu** [comment]
还有就是网络不稳定的时候有些图片下载下来是坏的。

**Comment by dixudx** [comment]
看看你的文本里面是不是用了中文的字符`，`，应该用英文的`,`。

网络不稳定，那就没办法了。你把没下载完成的图片删掉，重新运行脚本，会重新下载好的。之前下载过的，不会被覆盖和重新下载。

**Comment by weigeloveu** [comment]
多谢大佬，很玄妙，我用的都是英文字符，后来又用回车符隔开，还是不行。不能下全部的网站，只能下前面的一部分。
