### ISSUE TITLE
Cannot decode response data

### ISSUE THREAD

**Issue by weigeloveu** [dixudx/tumblr-crawler#45]
ead?type=video&num=50&start=0                                      Cannot decode response data from URL http://u44002.tumblr.com/api/read?type=video&num=50&start=0
Cannot decode response data from URL http://u44002.tumblr.com/api/read?type=video&num=50&start=0                                      Cannot decode response data from URL http://u44002.tumblr.com/api/read?type=video&num=50&start=0
Cannot decode response data from URL http://u44002.tumblr.com/api/read?type=video&num=50&start=0                                      Cannot decode response data from URL http://u44002.tumblr.com/api/read?type=video&num=50&start=0
Cannot decode response data from URL http://u44002.tumblr.com/api/read?type=video&num=50&start=0                                      Cannot decode response data from URL http://u44002.tumblr.com/api/read?type=video&num=50&start=0
Cannot decode response data from URL http://u44002.tumblr.com/api/read?type=video&num=50&start=0                                      Cannot decode response data from URL http://u44002.tumblr.com/api/read?type=video&num=50&start=0

**Comment by dixudx** [comment]
@weigeloveu Refer to #39.

The reason is that the site you want to download from contains non-decoded characters.
