### ISSUE TITLE
使用Shadowsock作为代理，提示Connect abort

### ISSUE THREAD

**Issue by k2000ghm** [dixudx/tumblr-crawler#50]
代理写

{
    "http": "sock5://127.0.0.1:1080",
    "https": "sock5://127.0.0.1:1080"
}

然后无论是
启用系统代理-全局
还是
启用系统代理-PAC
还是
不启用系统代理

都无法访问（这时候Chrome能通过sock5:127.0.0.1:1080出去）

改成

{
    "http": "http://127.0.0.1:1080",
    "https": "http://127.0.0.1:1080"
}

然后开全局就可以了

**Comment by YanfirePRO** [comment]
socks5报错Connection aborted， 改成http虽然不报错，但也没有取回数据。有什么解决方法么？

**Comment by dixudx** [comment]
@k2000ghm 是`socks5`, 不是`sock5`

```
{
    "http": "socks5://127.0.0.1:1080",
    "https": "socks5://127.0.0.1:1080"
}
```

**Comment by dixudx** [comment]
> socks5报错Connection aborte

@YanfirePRO 检查你的socks是不是能正常work，是不能随便改成http的，除非你把socks5转成了http的proxy

**Comment by YanfirePRO** [comment]
@dixudx chrome通过SwitchySharp设置socks5是可以出去的。
