### ISSUE TITLE
Can't Download Video

### ISSUE THREAD

**Issue by k2000ghm** [dixudx/tumblr-crawler#51]
I run the script and get the result like:

Downloading video_133163997.mp4 from https://player.vimeo.com/video/133163997?title=0&byline=0&portrait=0.

Finish Downloading All the videos from xxx

I have the video files but there size are abnormal ( Only 10K-20K）

I can open the url in my explorer and see the video

**Comment by dixudx** [comment]
Please retry downloading it.
