### ISSUE TITLE
Cannot decode response data from URL

### ISSUE THREAD

**Issue by whitelok** [dixudx/tumblr-crawler#53]
Hi 作者，
我在使用您的代码的时候 无意中发现 很多tumblr的帖子里面藏有漏洞攻击代码，藏有该代码的帖子您的代码基本都不能下载。
如 http://chinaxuyun.tumblr.com 的URL: http://chinaxuyun.tumblr.com/api/read?type=photo&num=50&start=100
故可添加`import defusedexpat`
并替换tumblr-photo-video-ripper.py中的第201行代码如下：

```
data = xmltodict.parse(response.content, expat=defusedexpat.pyexpat)
```

**Comment by whitelok** [comment]
参考资料:
https://www.rddoc.com/doc/Python/3.6.0/zh/library/xml/

**Comment by dixudx** [comment]
@whitelok Thanks for your suggestion. Would you please submit a PR to fix this if you're available ? Thanks for your contribution.

**Comment by whitelok** [comment]
添加xml非法字符清理
参考文献：
https://stackoverflow.com/questions/19652897/parsing-xml-with-not-well-formed-characters-in-python

**Comment by dixudx** [comment]
fixed in #59.
close it.
