### ISSUE TITLE
python 3 是不是用不了？

### ISSUE THREAD

**Issue by lifangzheng** [dixudx/tumblr-crawler#6]
RT

**Comment by dixudx** [comment]
@lifangzheng It should still work on Python3.

However I've not tested against Python3. It works well on Python 2.6 and Python 2.7.

You can have a try on Python 3.

**Comment by dixudx** [comment]
@lifangzheng 

I've just run a quick test on Python3. All work well.

**Comment by lifangzheng** [comment]
THX!!
