### ISSUE TITLE
Error when downloading defusedexpat

### ISSUE THREAD

**Issue by RonaldBolado** [dixudx/tumblr-crawler#61]

**Comment by dixudx** [comment]
> Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual
C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

@RonaldBolado Please install it.

**Comment by dixudx** [comment]
@RonaldBolado Please use latest commit. Fixed.
