### ISSUE TITLE
mp4 video file may broken if downloading with 10 threads.

### ISSUE THREAD

**Issue by whitelok** [dixudx/tumblr-crawler#62]
Hi 
I found an issue that mp4 video file may broken if downloading with 10 threads.
For example downloading sxmsts, this blog has many video and picture. It is OK for downloading picture with 10 threads. But downloading video with 10 threads, many video file will crash and can not play with video player. 
Should we download picture and video with different threads number?

**Comment by dixudx** [comment]
@whitelok You can try to download pictures and videos respectively. And choose the best number of threads in your needs.
