### ISSUE TITLE
请问tumblr的api是官方提供的码

### ISSUE THREAD

**Issue by Rockyzsu** [dixudx/tumblr-crawler#7]
大神你好，
请问tumblr的api是官方提供的码 ？ 如果不是，是通过什么办法取得的呢？？ 不吝赐教～

**Comment by dixudx** [comment]
The official api doc can be found [here](https://www.tumblr.com/docs/en/api/v2).

**Comment by Rockyzsu** [comment]
So does it ! Thx a lots !

**Comment by Rockyzsu** [comment]
After i had a quick review of the official doc, i only the only way to get info via api was:
api.tumblr.com/v2/blog/{blog-identifier}/posts[/type]?api_key={key}&[optional-params=]  GET API key

Is it the latest way to get the post info ? and the way you used can bypass the API KEY,  i don't see it in this office doc.

**Comment by dixudx** [comment]
I use [this v1 api](https://www.tumblr.com/docs/en/api/v1), which is the very basic api, only `/api/read`.

[v2 api](https://www.tumblr.com/docs/en/api/v2) has more features.
