### ISSUE TITLE
Downloading content(video/gif/picture)

### ISSUE THREAD

**Issue by Purefreeman** [dixudx/tumblr-crawler#70]
I've been running the program for a while now and no content seems to have been saved in the created for the accounts. The code just keeps on printing this out on the cmd. Is this normal?

Unknown xml-vulnerabilities from URL http://gucci.tumblr.com/api/read?type=photo&num=50&start=0
Unknown xml-vulnerabilities from URL http://gucci.tumblr.com/api/read?type=photo&num=50&start=0
Unknown xml-vulnerabilities from URL http://gucci.tumblr.com/api/read?type=photo&num=50&start=0
Unknown xml-vulnerabilities from URL http://gucci.tumblr.com/api/read?type=photo&num=50&start=0
Unknown xml-vulnerabilities from URL http://gucci.tumblr.com/api/read?type=photo&num=50&start=0

**Comment by dixudx** [comment]
@Purefreeman The return xml is invalid, which contains non-ASCII characters.
You can override this error by setting `MEDIA_NUM` to a larger value, for example `100`.
Give it a try.

**Comment by Purefreeman** [comment]
tried this and still getting the same outcome

**Comment by dixudx** [comment]
@Purefreeman Please follow #33 to debug the response content and find out the root cause.

**Comment by Purefreeman** [comment]
still the same error 
File "tumblr-photo-video-ripper.py", line 220, in _download_media
    print("Unknown xml-vulnerabilities from URL %s" % media_url)
OSError: raw write() returned invalid length 204 (should have been between 0 and 102)

**Comment by dixudx** [comment]
@Purefreeman Seems your proxy is not working as expected. Please check your proxy is working and enabled here.

**Comment by Purefreeman** [comment]
I'm not using any proxy

**Comment by rambda** [comment]
I figured this out. Just change
```
xml_cleaned = re.sub(u'[^\x20-\x7f]+',
                                     u'', response.content)
```
in the script to
```
xml_cleaned = re.sub(u'[^\x20-\x7f]+',
                                     u'', response.content.decode('utf-8'))
```

**Comment by dixudx** [comment]
@Purefreeman Could you have a try as @6XH mentioned above.

**Comment by Purefreeman** [comment]
Thank you for you assistant and taking the time to help. The error no longer shows up and the program works as it should .
