### ISSUE TITLE
建议优先下载原图

### ISSUE THREAD

**Issue by liyiecho** [dixudx/tumblr-crawler#75]
网页大图不一定是最高分辨率，比如这个http://bocchi.tumblr.com/post/142664656028

网页大图链接：https://68.media.tumblr.com/4a762c9aed5983bb14d11a3455865b22/tumblr_o5i2srwgyY1qaxnseo1_1280.jpg 其分辨率是1280*1895

而原图链接：
http://data.tumblr.com/4a762c9aed5983bb14d11a3455865b22/tumblr_o5i2srwgyY1qaxnseo1_raw.jpg  其分辨率却是2000*2961

当无法访问原图链接的时候，再去下载网页大图
希望可以修改一下

**Comment by dixudx** [comment]
Dup of #65.

Close it.
