### ISSUE TITLE
Skip reblogged content

### ISSUE THREAD

**Issue by KaMyKaSii** [dixudx/tumblr-crawler#78]
Please add a parameter to skip reblogged content. So only the blog's own content will be downloaded

**Comment by dixudx** [comment]
@KaMyKaSii I did not have too much bandwidth for this feature. Would you like to pick it up?

**Comment by KaMyKaSii** [comment]
@dixudx sorry but I do not have any development skills. If you qualify to do this, make it in your time. A similar project has this option, if it helps:
https://github.com/dannyvoid/Tumblrchive

**Comment by ybs1013** [comment]
恩 已经收到！
