### ISSUE TITLE
Error in script execution

### ISSUE THREAD

**Issue by KaMyKaSii** [dixudx/tumblr-crawler#79]
Error while executing the script without any parameters (in order to download users from the sites.txt file) by QPython 2.2.3-1 for Android

/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/scripts/tumblr-crawler-master/tumblr-photo-video-ripper.py" && exit
lr-photo-video-ripper.py" && exit       <
1. Please create file sites.txt under this same directory.
2. In sites.txt, you can specify tumblr sites separated by comma/space/tab/CR. Accept multiple lines of text
3. Save the file and retry.

Sample File Content:
site1,site2

Or use command line options:

Sample:
python tumblr-photo-video-ripper.py site1,site2

Traceback (most recent call last):
  File "/storage/emulated/0/qpython/scripts/tumblr-crawler-master/tumblr-photo-video-ripper.py", line 287, in <module>
    usage()
  File "/storage/emulated/0/qpython/scripts/tumblr-crawler-master/tumblr-photo-video-ripper.py", line 232, in usage
    print(u"未找到sites.txt文件，请创建.\n"
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
1|p8000:/ $

**Comment by dixudx** [comment]
@KaMyKaSii The script has not been tested against `Android`. You can try to insert some sites in `sites.txt`.

**Comment by KaMyKaSii** [comment]
@dixudx but that's exactly what I did. Adding "applegirl18" to sites.txt and running the script without any parameters leads to the error of the main post. It is only working when I execute the command using the blog in question as a parameter

**Comment by dixudx** [comment]
Fixed. @KaMyKaSii Please try to use latest code.

**Comment by KaMyKaSii** [comment]
@dixudx yes, now it's working perfectly. Thank you!
