### ISSUE TITLE
Downloaded video is corruption and not completed. Only has 243 bytes

### ISSUE THREAD

**Issue by Rockyzsu** [dixudx/tumblr-crawler#8]
Hi I checked some video files downloaded in the folder that were corruption and not completed. The size of the file only 243 bytes or less.  Is this blocked or restricted by the tumblr site ?

**Comment by dixudx** [comment]
It is blocked by the GFW. You can use a proxy. Please refer to [Proxy Usage](https://github.com/dixudx/tumblr-crawler#use-proxies-optional).

**Comment by Rockyzsu** [comment]
No. 
My network was connected to HK directly with high speed network. 
BTW, thanks for your reply

**Comment by dixudx** [comment]
I've tested using my own proxy. And all works well.

Would you mind to paste some detailed log ?

**Comment by bravolover520** [comment]
It is because this file is not a valid file, you can look at the status code that is returned.

**Comment by dixudx** [comment]
I used to encounter such problems. Actually It is because the data can not be successfully downloaded and written to file. And that is why a proxy is needed when such situation occurs.
