### ISSUE TITLE
只能下载图片 不能下载视频

### ISSUE THREAD

**Issue by zhanghan328** [dixudx/tumblr-crawler#9]
怎么解决呢?

**Comment by dixudx** [comment]
@zhanghan328 any detailed log?

Have you used a proxy ? Due to GFW, you may need to a proxy to bypass the wall.

For the configuration of such proxies, pls refer to [使用代理](https://github.com/dixudx/tumblr-crawler/blob/master/README_CN.md#使用代理-可选).
